include: package:lint/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore
    argument_type_not_assignable: ignore
    avoid_dynamic_calls: ignore
    avoid_print: ignore
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - lib/injection.config.dart
