name: valkyrie_app
description: The app for Valkyrie.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  another_flushbar: ^1.12.30
  calendar_time: ^2.2.0
  collection: ^1.17.1
  cyclop: ^0.6.2
  dartz: ^0.10.1
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.18.6
  flutter_typeahead: ^4.6.2
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  hive: ^2.2.3
  http_parser: ^4.0.2
  image_cropper: ^5.0.0
  # image_downloader: ^0.31.0
  image_picker: ^0.8.9
  injectable: ^2.1.2
  intl: ^0.17.0
  json_annotation: ^4.8.1
  path_provider: ^2.0.15
  photo_view: ^0.14.0
  transparent_image: ^2.0.1
  web_socket_channel: ^2.4.0
  webview_flutter: ^4.2.2

dev_dependencies:
  bloc_test: ^9.1.3
  build_runner: null
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.0
  lint: ^2.1.2
  mocktail: ^0.3.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
flutter_native_splash:
  color: "#35383E"
  image: assets/logo.png
