name: valkyrie_app
description: The app for Valkyrie.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  another_flushbar: ^1.10.28
  calendar_time: ^2.0.0
  cyclop: ^0.5.2
  dartz: ^0.10.1
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.2+1
  flutter_typeahead: ^3.2.4
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  hive: ^2.0.6
  http_parser: ^4.0.0
  image_cropper: ^1.5.0
  image_downloader: ^0.31.0
  image_picker: ^0.8.4+11
  injectable: ^1.5.3
  intl: ^0.17.0
  path_provider: ^2.0.9
  photo_view: ^0.13.0
  transparent_image: ^2.0.0
  web_socket_channel: ^2.1.0
  webview_flutter: ^3.0.1

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: null
  built_value: ^8.1.4
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.1
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  hive_generator: ^1.1.2
  injectable_generator: ^1.5.2
  lint: ^1.8.2
  mocktail: ^0.3.0

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon/icon.png'

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
flutter_native_splash:
  color: '#35383E'
  image: assets/logo.png
