/// Flutter icons App
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/App.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const String? _kFontPkg = null;

  static const IconData hammer =
      // ignore: avoid_redundant_argument_values
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gavel =
      // ignore: avoid_redundant_argument_values
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData infocircle =
      // ignore: avoid_redundant_argument_values
      IconData(0xf05a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link =
      // ignore: avoid_redundant_argument_values
      IconData(0xf0c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData usertimes =
      // ignore: avoid_redundant_argument_values
      IconData(0xf235, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData commentalt =
      // ignore: avoid_redundant_argument_values
      IconData(0xf27a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hashtag =
      // ignore: avoid_redundant_argument_values
      IconData(0xf292, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData userfriends =
      // ignore: avoid_redundant_argument_values
      IconData(0xf500, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData userlock =
      // ignore: avoid_redundant_argument_values
      IconData(0xf502, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
