name: Analyze and Test

on:
  pull_request:
  push:

jobs:
  build:
    name: Analyze & Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone flutter repository from stable channel with the latest version
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Test code
        run: flutter test
